# Generated by Django 3.2.5 on 2021-08-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('apellido', models.CharField(max_length=64)),
                ('puntaje', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=100)),
                ('respuesta1', models.CharField(max_length=100)),
                ('respuesta2', models.CharField(max_length=100)),
                ('respuesta3', models.CharField(max_length=100)),
                ('respuesta4', models.CharField(max_length=100)),
                ('correcta', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('Politica', 'Politica'), ('Geografica', 'Geografia'), ('Naturaleza', 'Naturaleza'), ('Cultura', 'Cultura'), ('Historia', 'Historia')], default='Politica', max_length=64)),
                ('dificultad', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preguntas', models.ManyToManyField(blank=True, to='preguntas.Pregunta')),
            ],
        ),
    ]
