# Generated by Django 3.2.5 on 2021-08-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0002_auto_20210824_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='respondida',
            field=models.BooleanField(default=False),
        ),
    ]
