# Generated by Django 3.2.5 on 2021-08-24 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0003_pregunta_respondida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preguntasrespondidas',
            name='preguntas',
        ),
        migrations.AddField(
            model_name='preguntasrespondidas',
            name='preguntas',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='preguntas.pregunta'),
        ),
    ]
