# Generated by Django 3.2.5 on 2021-08-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0004_auto_20210824_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='respondida',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='orden',
            field=models.IntegerField(default=1),
        ),
    ]
