# Generated by Django 3.2.5 on 2021-08-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0005_auto_20210824_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='puntaje_total',
            field=models.IntegerField(default=0),
        ),
    ]
