# Generated by Django 3.2.5 on 2021-08-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0007_auto_20210825_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=100)),
                ('respuesta1', models.CharField(max_length=100)),
                ('respuesta2', models.CharField(max_length=100)),
                ('respuesta3', models.CharField(max_length=100)),
                ('respuesta4', models.CharField(max_length=100)),
                ('correcta', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('Politica', 'Politica'), ('Geografica', 'Geografia'), ('Naturaleza', 'Naturaleza'), ('Cultura', 'Cultura'), ('Historia', 'Historia')], default='Politica', max_length=64)),
                ('dificultad', models.IntegerField(default=1)),
                ('orden', models.IntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='PreguntasRespondidas',
        ),
    ]
