# Generated by Django 3.2.5 on 2021-08-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0008_auto_20210827_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='categoria',
            field=models.CharField(choices=[('Politica', 'Politica'), ('Geografia', 'Geografia'), ('Naturaleza', 'Naturaleza'), ('Cultura', 'Cultura'), ('Historia', 'Historia')], default='Politica', max_length=64),
        ),
        migrations.AlterField(
            model_name='preguntacategoria',
            name='categoria',
            field=models.CharField(choices=[('Politica', 'Politica'), ('Geografia', 'Geografia'), ('Naturaleza', 'Naturaleza'), ('Cultura', 'Cultura'), ('Historia', 'Historia')], default='Politica', max_length=64),
        ),
    ]
