# Generated by Django 3.2.5 on 2021-08-31 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0009_auto_20210827_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='apellido',
        ),
    ]
